import Topo from "./componentes/header/page";
import Rodape from "./componentes/footer/page";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Topo/>
        {children}
        <Rodape/>
        </body>
    </html>
  );
}
